name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v2
        with:
          github_user_name: syncropal
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist
